
# SEO settings
title: "Nan Jiang's "
title2: " Site" # default: ""
description: "my personal blogger site."
keywords: "NLP, CS, Paper commeonts."
url: http://jiangnanhugo.github.io/blog # site url
#baseurl: "/blog" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io
theme: minimal-mistakes-jekyll

google_analytics: UA-91769229-1
repo: http://github.com/jiangnanhugo
disqus_shortname: "nanjiang"
twitter_username: "nanjiang"
comments: true



# Build settings
permalink   : /:year/:title/
markdown    : kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded


# Author settings
author:
  name     : "Nan Jiang"
  job      : "Graduate Student"
  bio      : "Gone with the wind."
  email    : jiangnan.hugo@gmail.com
  url      : http://jiangnanhugo.github.io
  github   : http://github.com/jiangnanhugo
  twitter  : https://twitter.com/jiangnan_hugo
  facebook : https://www.facebook.com/profile.php?id=1257583160
  linkedin : https://www.linkedin.com/in/%E6%A5%A0-%E5%A7%9C-097922aa/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@jiangnan_hugo"

plugins:
  - bourbon
  - jekyll-paginate-v2

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
