#-------------------------------
# Site Settings
title: Nan Jiang (姜楠)
logo: # You can add own logo. For example '/images/logo.png'.
author: Nan Jiang
description: Walking in the wind.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'About'
      url: '/about/'


#-------------------------------
# Google Analytics
google-analytics: UA-91769229-1
